name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Start a Postgres service container for DB tests
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mytestdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Set up Node
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies in the server folder
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      # 4. Run normal tests (no DB needed)
      - name: Run Regular Tests
        working-directory: ./server
        run: npm test

      # 5. Run DB tests (populateDummyData, etc.)
      - name: Run DB Tests
        working-directory: ./server
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: admin
          DB_NAME: postgres
        run: npm run test:db
