name: CI

on:
  push:
    paths:
      - "server/**"
    branches: ["main", "develop"]
  pull_request:
    paths:
      - "server/**"
    branches: ["main", "develop"]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        working-directory: ./server
        run: npm install

      # Run Tests
      - name: Run Server Tests
        working-directory: ./server
        run: npm test
